development:
  adapter: postgresql
  database: glamkitdb_developement
  pool: 5
  timeout: 5000
  host: localhost
  username: glamkit
  password: password1
  
test:
  adapter: postgresql
  database: glamkitdb_test
  pool: 5
  timeout: 5000
  host: localhost
  username: glamkit
  password: password1

production:
  adapter: postgresql
  database: glamkitdb_production
  pool: 5
  timeout: 5000
